// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXZI5iEu9sPo0GVywF32aRcgg8IEdcNWo',
    appId: '1:478583735702:web:c236fc2e1c07bcaa6789b7',
    messagingSenderId: '478583735702',
    projectId: 'jumia-shop',
    authDomain: 'jumia-shop.firebaseapp.com',
    storageBucket: 'jumia-shop.appspot.com',
    measurementId: 'G-SZMRTRQ895',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-jnFaoujl7QglQ1KgllZs1mpGzvVY7a0',
    appId: '1:478583735702:android:b5ac8ecbcc9b56516789b7',
    messagingSenderId: '478583735702',
    projectId: 'jumia-shop',
    storageBucket: 'jumia-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP9REolFNFwP8C5UvpKEA2X1g2FVXs39E',
    appId: '1:478583735702:ios:711bba40c8ea381b6789b7',
    messagingSenderId: '478583735702',
    projectId: 'jumia-shop',
    storageBucket: 'jumia-shop.appspot.com',
    iosClientId: '478583735702-6995h5fo20rgegfcfghkqr7a3bkgu14j.apps.googleusercontent.com',
    iosBundleId: 'com.jumia.shop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP9REolFNFwP8C5UvpKEA2X1g2FVXs39E',
    appId: '1:478583735702:ios:711bba40c8ea381b6789b7',
    messagingSenderId: '478583735702',
    projectId: 'jumia-shop',
    storageBucket: 'jumia-shop.appspot.com',
    iosClientId: '478583735702-6995h5fo20rgegfcfghkqr7a3bkgu14j.apps.googleusercontent.com',
    iosBundleId: 'com.jumia.shop',
  );
}
